### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by NameLmao** [KSean222/py_cold_clear#1]
All file paths I provide come up with invalid

**Comment by analog-hors** [comment]
Can you please provide steps to reproduce the issue as well as any relevant debug logs? Note that the library uses `ctypes.cdll.LoadLibrary` to load the library, so any relevant caveats should be explained in https://docs.python.org/3/library/ctypes.html.

**Comment by NameLmao** [comment]
![image](https://user-images.githubusercontent.com/72682146/140593888-d56a8c0b-f504-4f05-ae0a-efd7282dace7.png)

**Comment by analog-hors** [comment]
You need to provide the path to the dynamic library file (`.dll` on Windows), not the repository source code. You can build it in the CC repo by building the `c-api` target. Make sure that the DLL is compatible with these bindings; The commit the bindings have been updated for is listed at the top of `__init__.py`. Also ensure that the bitness matches the Python interpreter's bitness.

**Comment by NameLmao** [comment]
Is the dynamic library in the cold clear repository itself or do I have to make my own file for the dynamic library?

**Comment by analog-hors** [comment]
Build artifacts tend not to be distributed with source code. As far as I know, there are also no releases. You will likely have to build it yourself.

**Comment by NameLmao** [comment]
I don't know a lot about building dynamic libraries, do you have any guides that can help me with it?

**Comment by analog-hors** [comment]
After installing Rust, running `cargo build --release -p c-api` in the root directory of the repo should build the DLL in the `target/release` folder. Consider looking at the Rust book.

**Comment by NameLmao** [comment]
After it builds the files I just insert the file location into the program?

**Comment by analog-hors** [comment]
That should work. All it needs is the path to the dynamic library, which you can place anywhere you want as long as the path is correct.

**Comment by NameLmao** [comment]
Traceback (most recent call last):
  File "C:\Users\\Downloads\py_cold_clear-master\py_cold_clear-master\__init__.py", line 361, in <module>
    with CCHandle.launch(CCOptions.default(), CCWeights.default()) as bot:
  File "C:\Users\\Downloads\py_cold_clear-master\py_cold_clear-master\__init__.py", line 202, in launch
    return CCHandle(ctypes.cast(COLD_CLEAR_LIB.cc_launch_async(ctypes.byref(options), ctypes.byref(weights)), ctypes.c_void_p))
OSError: exception: access violation reading 0x0000000000000000

Got this error when entering the file location to the dynamic library

**Comment by analog-hors** [comment]
Have you ensured that the DLL is built from a compatible commit? Also ensure that the DLL bitness matches the bitness of the Python interpreter.

**Comment by NameLmao** [comment]
How would I check the bitness?

**Comment by NameLmao** [comment]
Just checked all the commits, none of them have the same ID as the last commit the interpreter is compatible with

**Comment by analog-hors** [comment]
You must have missed https://github.com/MinusKelvin/cold-clear/commit/f8a97dba7c3e6049a77534a15686a2832c9a0b59.

**Comment by NameLmao** [comment]
That's probably the issue, I'll see if that solves it

**Comment by NameLmao** [comment]
It seems to be a bitness issue

**Comment by analog-hors** [comment]
Python tells you the bitness of the interpreter on the REPL startup. There's a few ways of checking the bitness of DLLs. I use the Unix `file` utility. You should probably use whatever is convenient.

**Comment by analog-hors** [comment]
oops

**Comment by NameLmao** [comment]
Both are 64 bit files
